services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/expensesdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mariadb

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: expensesdb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  mariadb_data:
