spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/expensesdb
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
  messages:
    basename: i18n/messages
    encoding: UTF-8
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://expenses.alexander-kiemle.de}

servers:
  allowed-servers: ${ALLOWED_SERVERS:https://expenses.alexander-kiemle.de}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

logging:
  level:
    root: INFO
    de.expenses: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO
