name: Deploy to Server

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # -- FRONTEND BUILD --
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build frontend
        run: |
          npm install --legacy-peer-deps
          npm run build
        working-directory: ./frontend

      # -- BACKEND BUILD --
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build backend with Maven
        run: mvn clean package -DskipTests
        working-directory: ./backend

      # -- PREPARE DEPLOY DIR --
      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp -r docker-compose.yml deploy/
          cp -r backend/target/*.jar deploy/backend.jar
          cp -r frontend/build deploy/frontend
        # optional: cp .env deploy/.env etc.

      # -- DEPLOY TO SERVER --
      - name: Copy deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "deploy/*"
          target: "/home/github/app"
          debug: true

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/github/app/deploy
            docker-compose up -d --build
